### PR TITLE
Fix/update db

### PR DESCRIPTION
**Pull request by Kaskat**
Latest CRUD fixes
Update DB

---
This change is [Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/4)

### CODE REVIEW

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/4)* status: all files reviewed, 3 unresolved discussions (waiting on @Kaskat and @tanyalev)

___
*[src/main/java/app/DB/Query.java, line 42 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27giGED2orTk3tt3qh:-M27giGED2orTk3tt3qi:b-400f44) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L42)):*
> ```
> "where issue.project_id = '" + parts[0] + "' and issue.number = " + parts[1];
> ```
это не безопасно, sql инъекция
___
*[src/main/java/app/DB/Query.java, line 56 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gr_Y5sB6GuHNME1j:-M27gr_Y5sB6GuHNME1k:bhzhmjm) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L56)):*
> ```
> '" + id + "'";
> ```
То же самое
___
*[src/main/java/app/DB/Query.java, line 60 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gq9W7lAi_0CNdL9p:-M27gq9W7lAi_0CNdL9q:bef397y) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L60)):*
> ```
> \'" + id + "\'";
> ```
То же самое

**Comment by Kaskat** [comment]
___
*[src/main/java/app/DB/Query.java, line 42 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27giGED2orTk3tt3qh:-M28riCw3M_JujVjq-Xt:b-dqbnvq) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L42)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> "where issue.project_id = '" + parts[0] + "' and issue.number = " + parts[1];
> ```
это не безопасно, sql инъекция
</blockquote></details>

Уязвимость. Понял поправлю

**Comment by Kaskat** [comment]
___
*[src/main/java/app/DB/Query.java, line 56 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gr_Y5sB6GuHNME1j:-M28rvdK-pQj1z-mFEXL:b3kqu) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L56)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> '" + id + "'";
> ```
То же самое
</blockquote></details>

+

**Comment by Kaskat** [comment]
___
*[src/main/java/app/DB/Query.java, line 60 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gq9W7lAi_0CNdL9p:-M28ryB8EITI9HgPeoMu:b3kqu) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L60)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> \'" + id + "\'";
> ```
То же самое
</blockquote></details>

+

**Review by Antheso — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/4)* status: all files reviewed, 3 unresolved discussions (waiting on @Kaskat and @tanyalev)

___
*[src/main/java/app/DB/Query.java, line 42 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27giGED2orTk3tt3qh:-M2IQsB58EJZyOWU-rOs:bs8y2mg) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L42)):*
<details><summary><i>Previously, Kaskat (Kaskat) wrote…</i></summary><blockquote>

Уязвимость. Понял поправлю
</blockquote></details>

Не поправил
___
*[src/main/java/app/DB/Query.java, line 56 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gr_Y5sB6GuHNME1j:-M2IQtaJ02bQHKwkiWUO:b6oud6c) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L56)):*
<details><summary><i>Previously, Kaskat (Kaskat) wrote…</i></summary><blockquote>

+
</blockquote></details>

И тут
___
*[src/main/java/app/DB/Query.java, line 60 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/4#-M27gq9W7lAi_0CNdL9p:-M2IQuHR1eUlIxADeRXU:b6oud6c) ([raw file](https://github.com/antheso/bugtracker-backend/blob/beb9e1f44b7d7e4ec997fb4da59616c854f254d5/src/main/java/app/DB/Query.java#L60)):*
<details><summary><i>Previously, Kaskat (Kaskat) wrote…</i></summary><blockquote>

+
</blockquote></details>

И тут

**Review by tanyalev — APPROVED** [review]

**Review by Antheso — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/4)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
