### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by Kaskat**
Add Logout
Add Registration
Update User logic

---
This change is [Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/5)

### CODE REVIEW

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/5)* status: all files reviewed, 2 unresolved discussions (waiting on @Kaskat and @tanyalev)

___
*[src/main/java/app/Entities/User/UserController.java, line 69 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/5#-M27hpEr9KOnOMyKyUgR:-M27hpEr9KOnOMyKyUgS:bc184rd) ([raw file](https://github.com/antheso/bugtracker-backend/blob/5a4d10673fe59b5d723278ac5923e2fe08f40376/src/main/java/app/Entities/User/UserController.java#L69)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     user.getName(),
>                     user.getLastName(),
>                     user.getLoginName(),
>                     user.getPassword()
> ```
</details>

нам нужен будет еще и email
___
*[src/main/java/app/Javalin/JavalinManager.java, line 69 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/5#-M27hb5112FHn41NLepm:-M27hb5112FHn41NLepn:b-ryhpsg) ([raw file](https://github.com/antheso/bugtracker-backend/blob/5a4d10673fe59b5d723278ac5923e2fe08f40376/src/main/java/app/Javalin/JavalinManager.java#L69)):*
> ```
> //            ctx.status(500);
> ```
а почему закомментил?

**Comment by Kaskat** [comment]
___
*[src/main/java/app/Javalin/JavalinManager.java, line 69 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/5#-M27hb5112FHn41NLepm:-M28r4mcAvSx8QTliNzD:b-bceeia) ([raw file](https://github.com/antheso/bugtracker-backend/blob/5a4d10673fe59b5d723278ac5923e2fe08f40376/src/main/java/app/Javalin/JavalinManager.java#L69)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> //            ctx.status(500);
> ```
а почему закомментил?
</blockquote></details>

Фронт постоянно крашит, будет время, отдельно займусь этим вопросом

**Comment by Kaskat** [comment]
___
*[src/main/java/app/Entities/User/UserController.java, line 69 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/5#-M27hpEr9KOnOMyKyUgR:-M28rMzV75zGVKO-liOt:b4ngdg5) ([raw file](https://github.com/antheso/bugtracker-backend/blob/5a4d10673fe59b5d723278ac5923e2fe08f40376/src/main/java/app/Entities/User/UserController.java#L69)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
>                     user.getName(),
>                     user.getLastName(),
>                     user.getLoginName(),
>                     user.getPassword()
> ```
нам нужен будет еще и email
</blockquote></details>

Ок, добавлю

Я ориентировался на фронт, добавь тогда и там email

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/5)* status: all files reviewed, 1 unresolved discussion (waiting on @Kaskat and @tanyalev)

___
*[src/main/java/app/Javalin/JavalinManager.java, line 69 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/5#-M27hb5112FHn41NLepm:-M2IQlB79u4ByGsZV5IG:b-o0kmyd) ([raw file](https://github.com/antheso/bugtracker-backend/blob/5a4d10673fe59b5d723278ac5923e2fe08f40376/src/main/java/app/Javalin/JavalinManager.java#L69)):*
<details><summary><i>Previously, Kaskat (Kaskat) wrote…</i></summary><blockquote>

Фронт постоянно крашит, будет время, отдельно займусь этим вопросом
</blockquote></details>

Верни плез

**Review by tanyalev — APPROVED** [review]

**Review by Antheso — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/5)* status: all files reviewed, 1 unresolved discussion (waiting on @Kaskat)

**Pull request merged**
