### PR TITLE
Update all code

### PR DESCRIPTION
**Pull request by Kaskat**
This change is [Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/7)

### CODE REVIEW

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/7)* status: all files reviewed, 4 unresolved discussions (waiting on @Kaskat, @Kycok-Ivana, and @tanyalev)

___
*[src/main/java/app/DB/Query.java, line 38 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3CjCg3340nPZZZj9mJ:-M3CjCg3340nPZZZj9mK:b-ecy6gu) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/DB/Query.java#L38)):*
> ```
> issue.deprecated
> ```
Вроде ж ушли от этого
___
*[src/main/java/app/DB/Query.java, line 61 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3Cj9u2CESCTn3hwqtr:-M3Cj9u2CESCTn3hwqts:b2bexjg) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/DB/Query.java#L61)):*
> ```
> //    public static String SELECT_COMMENT_BY_ISSUE_ID_RECURSIVE
> //           = "select comment.comment_id, comment.text, comment.user_id, buser.first_name, extract(epoch from timestamp) as timestamp from(WITH RECURSIVE included_numbers(deprecated, issue_number) AS (    SELECT deprecated, issue_number FROM \"BugTracker\".\"Issue\" WHERE issue_number = ?    UNION ALL    SELECT p.deprecated, p.issue_number    FROM included_numbers pr, \"BugTracker\".\"Issue\" p    WHERE p.issue_number = pr.deprecated)SELECT issue_number FROM included_numbers) inum inner join \"BugTracker\".\"Comment\" comment on inum.issue_number = comment.issue_number inner join \"BugTracker\".\"User\" buser on comment.user_id = buser.user_id";
> ```
Нужно?
___
*[src/main/java/app/Entities/Issue/Issue.java, line 12 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3CjMpv9CRLO_mmVCoO:-M3CjMpv9CRLO_mmVCoP:b4aaegq) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/Entities/Issue/Issue.java#L12)):*
> ```
> //id - issue_number //FAQ
> ```
Нужно?
___
*[src/main/java/app/Entities/Issue/Issue.java, line 64 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3CjOck8yRpbIV0ZbWL:-M3CjOck8yRpbIV0ZbWM:bx7ho45) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/Entities/Issue/Issue.java#L64)):*
> ```
> this.deprecated = deprecated;
> ```
Ушли от этого

**Comment by Kaskat** [comment]
___
*[src/main/java/app/DB/Query.java, line 38 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3CjCg3340nPZZZj9mJ:-M3G8FDx9BjeUDaD2EmH:buyy8rr) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/DB/Query.java#L38)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> issue.deprecated
> ```
Вроде ж ушли от этого
</blockquote></details>

К сожалению несовсем...

Я столкнулся с проблемой. После добавления нового Issue я немогу получить его id.
Пришлось оставить deprecated как маяк. Чтобы найти новое id по старому id (для обновления комментариев)

**Comment by Kaskat** [comment]
___
*[src/main/java/app/Entities/Issue/Issue.java, line 12 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3CjMpv9CRLO_mmVCoO:-M3GAEFA80ZOvVlNLPUj:b7dcr3s) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/Entities/Issue/Issue.java#L12)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> //id - issue_number //FAQ
> ```
Нужно?
</blockquote></details>

Убрал

**Comment by Kaskat** [comment]
___
*[src/main/java/app/DB/Query.java, line 61 at r1](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3Cj9u2CESCTn3hwqtr:-M3GACHJ-45OzXzo_hDd:bfen6c2) ([raw file](https://github.com/antheso/bugtracker-backend/blob/bb3e04b7a516c21544d3009127d55eae4951a65b/src/main/java/app/DB/Query.java#L61)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> //    public static String SELECT_COMMENT_BY_ISSUE_ID_RECURSIVE
> //           = "select comment.comment_id, comment.text, comment.user_id, buser.first_name, extract(epoch from timestamp) as timestamp from(WITH RECURSIVE included_numbers(deprecated, issue_number) AS (    SELECT deprecated, issue_number FROM \"BugTracker\".\"Issue\" WHERE issue_number = ?    UNION ALL    SELECT p.deprecated, p.issue_number    FROM included_numbers pr, \"BugTracker\".\"Issue\" p    WHERE p.issue_number = pr.deprecated)SELECT issue_number FROM included_numbers) inum inner join \"BugTracker\".\"Comment\" comment on inum.issue_number = comment.issue_number inner join \"BugTracker\".\"User\" buser on comment.user_id = buser.user_id";
> ```
Нужно?
</blockquote></details>

Убрал

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r2.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/7)* status: 27 of 28 files reviewed, 5 unresolved discussions (waiting on @Antheso, @Kaskat, @Kycok-Ivana, and @tanyalev)

___
*[src/main/java/app/Security/JWTAccessManager.java, line 37 at r2](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3GXWS-9waWVwj_G9BL:-M3GXWS-9waWVwj_G9BM:b-rif88y) ([raw file](https://github.com/antheso/bugtracker-backend/blob/a8891160dcfd7ceec3887e66be69f78418a058a6/src/main/java/app/Security/JWTAccessManager.java#L37)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> //    private boolean isAuthorized(Context context) {
> //        if (!JavalinJWT.containsJWT(context)) {
> //            return false;
> //        }
> //
> //        DecodedJWT jwt = JavalinJWT.getDecodedFromContext(context);
> //        return tokenStorage.get(jwt.getToken()) == null;
> //    }
> ```
</details>

Убрать

**Review by tanyalev — APPROVED** [review]

**Review by tanyalev — APPROVED** [review]

**Review by Antheso — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/7)* status: all files reviewed, 7 unresolved discussions (waiting on @Antheso, @Kaskat, and @Kycok-Ivana)

___
*[src/main/java/app/Entities/User/UserController.java, line 62 at r3](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3LK4Mg5Ipkv_iT8dYp:-M3LK4Mg5Ipkv_iT8dYq:b-cnw1su) ([raw file](https://github.com/antheso/bugtracker-backend/blob/8c04c1ff826ee3ce08872d3870c9b7920133bc73/src/main/java/app/Entities/User/UserController.java#L62)):*
> ```
> //        if (!BCrypt.checkpw(password, pas)) {
> ```
Убрать
___
*[src/main/java/app/Entities/User/UserDeserializer.java, line 21 at r3](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3LK6hL3wPTC9C6U1Sk:-M3LK6hL3wPTC9C6U1Sl:b-5cmgxj) ([raw file](https://github.com/antheso/bugtracker-backend/blob/8c04c1ff826ee3ce08872d3870c9b7920133bc73/src/main/java/app/Entities/User/UserDeserializer.java#L21)):*
> ```
> //        int salt = Integer.parseInt(Configuration.properties.getProperty("salt"));
> //        String hashedPassword = BCrypt.hashpw(password, BCrypt.gensalt(salt));
> ```
Убрать

**Comment by Kaskat** [comment]
___
*[src/main/java/app/Entities/User/UserController.java, line 62 at r3](https://reviewable.io/reviews/antheso/bugtracker-backend/7#-M3LK4Mg5Ipkv_iT8dYp:-M3MRP2P8FYTHqpAf_ba:b7demuz) ([raw file](https://github.com/antheso/bugtracker-backend/blob/8c04c1ff826ee3ce08872d3870c9b7920133bc73/src/main/java/app/Entities/User/UserController.java#L62)):*
<details><summary><i>Previously, Antheso (Bohdan) wrote…</i></summary><blockquote>

> ```
> //        if (!BCrypt.checkpw(password, pas)) {
> ```
Убрать
</blockquote></details>

Удолю

**Review by Antheso — APPROVED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/antheso/bugtracker-backend/7)* status: all files reviewed, 7 unresolved discussions (waiting on @Antheso, @Kaskat, and @Kycok-Ivana)

**Pull request merged**
